name: Sample Console App Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Clean
      run: dotnet clean src/pipelines/SampleConsoleApp/SampleConsoleApp.sln --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore src/pipelines/SampleConsoleApp/SampleConsoleApp.sln
    - name: Build
      run: dotnet build src/pipelines/SampleConsoleApp/SampleConsoleApp.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test src/pipelines/SampleConsoleApp/SampleConsoleApp.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src/pipelines/SampleConsoleApp/SampleConsoleApp.sln
    - name: Upload Sampl App Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SampleApp
        path: /home/runner/work/DeveloperCurriculum/DeveloperCurriculum/src/pipelines/SampleConsoleApp/SampleConsoleApp/bin/Debug/netcoreapp3.1/publish/
