name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Clean
      run: dotnet clean src/pipelines/SampleConsoleApp/SampleConsoleApp.sln --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore src/pipelines/SampleConsoleApp/SampleConsoleApp.sln
      inputs:
          command: restore
          projects: '$(serviceLocation)/**/*.csproj'
          includeNuGetOrg: true
    - name: Build
      run: dotnet build src/pipelines/SampleConsoleApp/SampleConsoleApp.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test src/pipelines/SampleConsoleApp/SampleConsoleApp.sln --no-build --verbosity normal
